services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

#  postgres_fraud:
#    container_name: postgres_fraud
#    image: postgres
#    environment:
#      POSTGRES_USER: fraud
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres_fraud:/data/postgres
#    ports:
#      - "5433:5432"
#    networks:
#      - postgres_fraud
#    restart: unless-stopped
#
#  postgres_customer:
#    container_name: postgres_customer
#    image: postgres
#    environment:
#      POSTGRES_USER: amigoscode
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres_customer:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres_customer
#    restart: unless-stopped

#  postgres_notification:
#    container_name: postgres_notification
#    image: postgres
#    environment:
#      POSTGRES_USER: amigoscode
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - postgres_notification:/data/postgres
#    ports:
#      - "5434:5432"
#    networks:
#      - postgres_notification
#    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
#    networks:
#      - postgres_customer
#      - postgres_fraud
#      - postgres_notification
    restart: unless-stopped

#networks:
#  postgres_customer:
#    driver: bridge
#  postgres_fraud:
#    driver: bridge
#  postgres_notification:
#    driver: bridge

volumes:
#  postgres_customer:
#  postgres_notification:
  pgadmin:
#  postgres_fraud: